export default {
    "hi": "https://www.lottoland.asia/hi/eurojackpot/results-winning-numbers/24-09-2021",
    "en-IE": "https://www.lottoland.ie/eurojackpot/results-winning-numbers/24-09-2021",
    "de-DE": "https://www.lottoland.com/eurojackpot/zahlen-quoten/24-09-2021",
    "hu-HU": "https://www.lottoland.eu/eurojackpot/lottoszamok/24-09-2021",
    "pt-BR": "https://www.lottoland.com/br/eurojackpot/resultados/24-09-2021",
    "en-GI": "https://www.lottoland.gi/eurojackpot/results-winning-numbers/24-09-2021",
    "en-IN": "https://www.lottoland.asia/eurojackpot/results-winning-numbers/24-09-2021",
    "en": "https://www.lottoland.com/en/eurojackpot/results-winning-numbers/24-09-2021",
    "en-ZA": "https://www.lottoland.co.za/eurojackpot/results-winning-numbers/24-09-2021",
    "en-MT": "https://www.lottoland.com/mt/eurojackpot/results-winning-numbers/24-09-2021",
    "en-NT": "https://www.lottoland.com/global/eurojackpot/results-winning-numbers/24-09-2021",
    "es": "https://www.lotoland.com/eurojackpot/resultados/24-09-2021",
    "es-MX": "https://www.lotoland.com/mx/eurojackpot/resultados/24-09-2021",
    "de-AT": "https://www.lottoland.at/eurojackpot/zahlen-quoten/24-09-2021",
    "en-NZ": "https://www.lottoland.com/nz/eurojackpot/results-winning-numbers/24-09-2021",
    "sv-SE": "https://www.lottoland.se/eurojackpot/resultat/24-09-2021",
    "ja": "https://www.lottoland.com/jp/eurojackpot/results-winning-numbers/24-09-2021",
    "sk": "https://www.lottoland.com/sk/eurojackpot/vysledky/24-09-2021",
    "en-AU": "https://www.lottoland.com.au/eurojackpot/results/24-09-2021",
    "pl": "https://www.lottoland.com/pl/eurojackpot/wyniki-numery-wygrane/24-09-2021",
    "en-GB": "https://www.lottoland.co.uk/eurojackpot/results-winning-numbers/24-09-2021",
}
